apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: client-backendconfig
spec:
  healthCheck:
    requestPath: /chat
    port: 3000
    type: HTTP
    checkIntervalSec: 15
    timeoutSec: 5
