apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: websocket-backendconfig
spec:
  timeoutSec: 86400
  healthCheck:
    requestPath: /health
    port: 8080
    type: HTTP
    checkIntervalSec: 15
    timeoutSec: 5
